<a href="https://colab.research.google.com/github/impo33ibru/dap-2024/blob/main/les04/lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа №4.
# Анализ данных пассажиров "Титаника"

Гибель Титаника – одно из самых печально известных кораблекрушений в истории.

15 апреля 1912 года во время своего первого плавания считавшийся «непотопляемым» «Титаник» затонул после столкновения с айсбергом.
К сожалению, спасательных шлюпок для всех находившихся на борту не хватило, в результате чего погибли 1502 из 2224 пассажиров и членов экипажа.

Используя набор данных titanic.csv выполните следующие 10 заданий.

In [ ]:
import numpy as np
import pandas as pd

1. Создайте DataFarame из файла titanic.csv, в качестве индекса используйте столбец "PassengerId"

In [ ]:
titanic_df = pd.read_csv("titanic.csv", index_col='PassengerId')
titanic_df

<div id="df-68a906a4-0f0e-4e35-adc7-03abcb33c82e" class="colab-df-container">
    <div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Survived</th>
      <th>Pclass</th>
      <th>Name</th>
      <th>Sex</th>
      <th>Age</th>
      <th>SibSp</th>
      <th>Parch</th>
      <th>Ticket</th>
      <th>Fare</th>
      <th>Cabin</th>
      <th>Embarked</th>
    </tr>
    <tr>
      <th>PassengerId</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>0</td>
      <td>3</td>
      <td>Braund, Mr. Owen Harris</td>
      <td>male</td>
      <td>22.0</td>
      <td>1</td>
      <td>0</td>
      <td>A/5 21171</td>
      <td>7.2500</td>
      <td>NaN</td>
      <td>S</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1</td>
      <td>1</td>
      <td>Cumings, Mrs. John Bradley (Florence Briggs Th...</td>
      <td>female</td>
      <td>38.0</td>
      <td>1</td>
      <td>0</td>
      <td>PC 17599</td>
      <td>71.2833</td>
      <td>C85</td>
      <td>C</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1</td>
      <td>3</td>
      <td>Heikkinen, Miss. Laina</td>
      <td>female</td>
      <td>26.0</td>
      <td>0</td>
      <td>0</td>
      <td>STON/O2. 3101282</td>
      <td>7.9250</td>
      <td>NaN</td>
      <td>S</td>
    </tr>
    <tr>
      <th>4</th>
      <td>1</td>
      <td>1</td>
      <td>Futrelle, Mrs. Jacques Heath (Lily May Peel)</td>
      <td>female</td>
      <td>35.0</td>
      <td>1</td>
      <td>0</td>
      <td>113803</td>
      <td>53.1000</td>
      <td>C123</td>
      <td>S</td>
    </tr>
    <tr>
      <th>5</th>
      <td>0</td>
      <td>3</td>
      <td>Allen, Mr. William Henry</td>
      <td>male</td>
      <td>35.0</td>
      <td>0</td>
      <td>0</td>
      <td>373450</td>
      <td>8.0500</td>
      <td>NaN</td>
      <td>S</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>887</th>
      <td>0</td>
      <td>2</td>
      <td>Montvila, Rev. Juozas</td>
      <td>male</td>
      <td>27.0</td>
      <td>0</td>
      <td>0</td>
      <td>211536</td>
      <td>13.0000</td>
      <td>NaN</td>
      <td>S</td>
    </tr>
    <tr>
      <th>888</th>
      <td>1</td>
      <td>1</td>
      <td>Graham, Miss. Margaret Edith</td>
      <td>female</td>
      <td>19.0</td>
      <td>0</td>
      <td>0</td>
      <td>112053</td>
      <td>30.0000</td>
      <td>B42</td>
      <td>S</td>
    </tr>
    <tr>
      <th>889</th>
      <td>0</td>
      <td>3</td>
      <td>Johnston, Miss. Catherine Helen "Carrie"</td>
      <td>female</td>
      <td>NaN</td>
      <td>1</td>
      <td>2</td>
      <td>W./C. 6607</td>
      <td>23.4500</td>
      <td>NaN</td>
      <td>S</td>
    </tr>
    <tr>
      <th>890</th>
      <td>1</td>
      <td>1</td>
      <td>Behr, Mr. Karl Howell</td>
      <td>male</td>
      <td>26.0</td>
      <td>0</td>
      <td>0</td>
      <td>111369</td>
      <td>30.0000</td>
      <td>C148</td>
      <td>C</td>
    </tr>
    <tr>
      <th>891</th>
      <td>0</td>
      <td>3</td>
      <td>Dooley, Mr. Patrick</td>
      <td>male</td>
      <td>32.0</td>
      <td>0</td>
      <td>0</td>
      <td>370376</td>
      <td>7.7500</td>
      <td>NaN</td>
      <td>Q</td>
    </tr>
  </tbody>
</table>
<p>891 rows × 11 columns</p>
</div>
    <div class="colab-df-buttons">

  <div class="colab-df-container">
  <style>
    .colab-df-container {
      display:flex;
      gap: 12px;
    }

    .colab-df-convert {
      background-color: #E8F0FE;
      border: none;
      border-radius: 50%;
      cursor: pointer;
      display: none;
      fill: #1967D2;
      height: 32px;
      padding: 0 0 0 0;
      width: 32px;
    }

    .colab-df-convert:hover {
      background-color: #E2EBFA;
      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);
      fill: #174EA6;
    }

    .colab-df-buttons div {
      margin-bottom: 4px;
    }

    [theme=dark] .colab-df-convert {
      background-color: #3B4455;
      fill: #D2E3FC;
    }

    [theme=dark] .colab-df-convert:hover {
      background-color: #434B5C;
      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);
      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));
      fill: #FFFFFF;
    }
  </style>

  </div>


<div id="df-092a7fce-8110-4795-b732-2a722e226548">
  <button class="colab-df-quickchart" onclick="quickchart('df-092a7fce-8110-4795-b732-2a722e226548')"
            title="Suggest charts"
            style="display:none;">

  </button>

<style>
  .colab-df-quickchart {
      --bg-color: #E8F0FE;
      --fill-color: #1967D2;
      --hover-bg-color: #E2EBFA;
      --hover-fill-color: #174EA6;
      --disabled-fill-color: #AAA;
      --disabled-bg-color: #DDD;
  }

  [theme=dark] .colab-df-quickchart {
      --bg-color: #3B4455;
      --fill-color: #D2E3FC;
      --hover-bg-color: #434B5C;
      --hover-fill-color: #FFFFFF;
      --disabled-bg-color: #3B4455;
      --disabled-fill-color: #666;
  }

  .colab-df-quickchart {
    background-color: var(--bg-color);
    border: none;
    border-radius: 50%;
    cursor: pointer;
    display: none;
    fill: var(--fill-color);
    height: 32px;
    padding: 0;
    width: 32px;
  }

  .colab-df-quickchart:hover {
    background-color: var(--hover-bg-color);
    box-shadow: 0 1px 2px rgba(60, 64, 67, 0.3), 0 1px 3px 1px rgba(60, 64, 67, 0.15);
    fill: var(--button-hover-fill-color);
  }

  .colab-df-quickchart-complete:disabled,
  .colab-df-quickchart-complete:disabled:hover {
    background-color: var(--disabled-bg-color);
    fill: var(--disabled-fill-color);
    box-shadow: none;
  }

  .colab-df-spinner {
    border: 2px solid var(--fill-color);
    border-color: transparent;
    border-bottom-color: var(--fill-color);
    animation:
      spin 1s steps(1) infinite;
  }

  @keyframes spin {
    0% {
      border-color: transparent;
      border-bottom-color: var(--fill-color);
      border-left-color: var(--fill-color);
    }
    20% {
      border-color: transparent;
      border-left-color: var(--fill-color);
      border-top-color: var(--fill-color);
    }
    30% {
      border-color: transparent;
      border-left-color: var(--fill-color);
      border-top-color: var(--fill-color);
      border-right-color: var(--fill-color);
    }
    40% {
      border-color: transparent;
      border-right-color: var(--fill-color);
      border-top-color: var(--fill-color);
    }
    60% {
      border-color: transparent;
      border-right-color: var(--fill-color);
    }
    80% {
      border-color: transparent;
      border-right-color: var(--fill-color);
      border-bottom-color: var(--fill-color);
    }
    90% {
      border-color: transparent;
      border-bottom-color: var(--fill-color);
    }
  }
</style>
</div>
    </div>
  </div>

2. Просмотрите первые 6 строк

In [ ]:
titanic_df.head(6)

3. Выведите описание данных

In [ ]:
titanic_df.describe()

<div id="df-6ebbaa56-4505-4233-aeb5-4b467c204bf7" class="colab-df-container">
    <div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Survived</th>
      <th>Pclass</th>
      <th>Age</th>
      <th>SibSp</th>
      <th>Parch</th>
      <th>Fare</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>count</th>
      <td>891.000000</td>
      <td>891.000000</td>
      <td>714.000000</td>
      <td>891.000000</td>
      <td>891.000000</td>
      <td>891.000000</td>
    </tr>
    <tr>
      <th>mean</th>
      <td>0.383838</td>
      <td>2.308642</td>
      <td>29.699118</td>
      <td>0.523008</td>
      <td>0.381594</td>
      <td>32.204208</td>
    </tr>
    <tr>
      <th>std</th>
      <td>0.486592</td>
      <td>0.836071</td>
      <td>14.526497</td>
      <td>1.102743</td>
      <td>0.806057</td>
      <td>49.693429</td>
    </tr>
    <tr>
      <th>min</th>
      <td>0.000000</td>
      <td>1.000000</td>
      <td>0.420000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>25%</th>
      <td>0.000000</td>
      <td>2.000000</td>
      <td>20.125000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>7.910400</td>
    </tr>
    <tr>
      <th>50%</th>
      <td>0.000000</td>
      <td>3.000000</td>
      <td>28.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>14.454200</td>
    </tr>
    <tr>
      <th>75%</th>
      <td>1.000000</td>
      <td>3.000000</td>
      <td>38.000000</td>
      <td>1.000000</td>
      <td>0.000000</td>
      <td>31.000000</td>
    </tr>
    <tr>
      <th>max</th>
      <td>1.000000</td>
      <td>3.000000</td>
      <td>80.000000</td>
      <td>8.000000</td>
      <td>6.000000</td>
      <td>512.329200</td>
    </tr>
  </tbody>
</table>

  </div>

4. Сколько мужчин / женщин находилось на борту?

In [ ]:
male = titanic_df['Sex'] == 'male'
female = titanic_df['Sex'] == 'female'
print("На борту:")
print("Мужчин -", male.sum())
print("Женщин -", female.sum())

На борту:
Мужчин - 577
Женщин - 314

4. Выведите распределение переменной Pclass (социально-экономический статус) и это же распределение, только для мужчин / женщин по отдельности. Сколько было мужчин 2-го класса

In [ ]:
pclass = titanic_df['Pclass']
print("Социально-экономический статус:\n", pclass.value_counts())
print("\nСоциально-экономический статус для мужчин:\n", pclass[male].value_counts())
print("\nСоциально-экономический статус для женщин:\n", pclass[female].value_counts())
count = pclass[male].value_counts().loc[2]
print("\nКоличество мужчин в 2 классе:", count)

Социально-экономический статус:
 Pclass
3    491
1    216
2    184
Name: count, dtype: int64

Социально-экономический статус для мужчин:
 Pclass
3    347
1    122
2    108
Name: count, dtype: int64

Социально-экономический статус для женщин:
 Pclass
3    144
1     94
2     76
Name: count, dtype: int64

Количество мужчин в 2 классе: 108

5. Каковы медиана и среднеквадрати́чное отклонение платежей (Fare)? Округлите до 2 десятичных знаков.

In [ ]:
median = round(titanic_df['Fare'].median(), 2)
std = round(titanic_df['Fare'].std(), 2)
print("Медиана:", median)
print("Среднеквадрати́чное отклонение:", std)

Медиана: 14.45
Среднеквадрати́чное отклонение: 49.69

6. Правда ли, что люди моложе 30 лет выживали чаще, чем люди старше 60 лет? Каковы доли выживших в обеих группах?

In [ ]:
younger = titanic_df[titanic_df['Age'] < 30]
older = titanic_df[titanic_df['Age'] > 60]
ysurvived = round(younger['Survived'].mean(), 2)
osurvived = round(older['Survived'].mean(), 2)
print("Доля выживанания людей моложе 30 лет:", ysurvived)
print("Доля выживания людей старше 60 лет:", osurvived)
print("Люди моложе 30 лет выживали чаще!") if ysurvived > osurvived else print("Данное утверждение неверно")

In [ ]:
Доля выживанания людей моложе 30 лет: 0.41
Доля выживания людей старше 60 лет: 0.23
Люди моложе 30 лет выживали чаще!

7. Правда ли, что женщины выживали чаще мужчин? Каковы доли выживших в обеих группах?

In [ ]:
male = titanic_df[titanic_df['Sex'] == "male"]
female = titanic_df[titanic_df['Sex'] == "female"]
msurvived = round(male['Survived'].mean(), 2)
fsurvived = round(female['Survived'].mean(), 2)
print("Доля выживания мужчин:", msurvived)
print("Доля выживания женщин:", fsurvived)
print("Женщины выживали чаще мужчин!") if fsurvived > msurvived else print("Данное утверждение неверно")

In [ ]:
Доля выживания мужчин: 0.19
Доля выживания женщин: 0.74
Женщины выживали чаще мужчин!

8.  Найдите самое популярное имя среди пассажиров Титаника мужского пола?

In [ ]:
name = male['Name'].str.split(" ").str[2]
print(name)
print("\n"f"Наиболее часто встречаемое имя мужского пола - {name.mode().iloc[0]}")

In [ ]:
PassengerId
1           Owen
5        William
6          James
7        Timothy
8          Gosta
         ...
884    Frederick
885        Henry
887       Juozas
890         Karl
891      Patrick
Name: Name, Length: 577, dtype: object

Наиболее часто встречаемое имя мужского пола - William



9. Как отличается средний возраст мужчин / женщин в зависимости от класса обслуживания? Выберите верные утверждения:

    В среднем мужчины 1-го класса старше 40 лет
    В среднем женщины 1-го класса старше 40 лет
    Мужчины всех классов в среднем старше женщин того же класса
    В среднем люди в 1 классе старше, чем во 2-ом, а те старше представителей 3-го класса

In [ ]:
mean_age = titanic_df.groupby(['Pclass', 'Sex'])['Age'].mean()
print(mean_age)

men_first_class = titanic_df[(titanic_df['Pclass'] == 1) & (titanic_df['Sex'] == 'male')]
women_first_class = titanic_df[(titanic_df['Pclass'] == 1) & (titanic_df['Sex'] == 'female')]

men_second_class = titanic_df[(titanic_df['Pclass'] == 2) & (titanic_df['Sex'] == 'male')]
women_second_class = titanic_df[(titanic_df['Pclass'] == 2) & (titanic_df['Sex'] == 'female')]

men_third_class = titanic_df[(titanic_df['Pclass'] == 3) & (titanic_df['Sex'] == 'male')]
women_third_class = titanic_df[(titanic_df['Pclass'] == 3) & (titanic_df['Sex'] == 'female')]


men_first_class_age = round(men_first_class['Age'].mean(), 2)
women_first_class_age = round(women_first_class['Age'].mean(), 2)

men_second_class_age = round(men_second_class['Age'].mean(), 2)
women_second_class_age = round(women_second_class['Age'].mean(), 2)

men_third_class_age = round(men_third_class['Age'].mean(), 2)
women_third_class_age = round(women_third_class['Age'].mean(), 2)


print("\nАнализ утверждений:")


print("1. В среднем мужчины 1-го класса старше 40 лет:", "Верно!" if men_first_class_age > 40 else "Неверно!")


print("2. В среднем женщины 1-го класса старше 40 лет:", "Верно!" if women_first_class_age > 40 else "Неверно!")


men_older_women = (
    men_first_class_age > women_first_class_age and
    men_second_class_age > women_second_class_age and
    men_third_class_age > women_third_class_age
)

print("3. Мужчины всех классов в среднем старше женщин того же класса:", "Верно!" if men_older_women else "Неверно!")


first_class_older = (men_first_class_age > men_second_class_age > men_third_class_age and
                     women_first_class_age > women_second_class_age > women_third_class_age)
print("4. В среднем люди в 1 классе старше, чем во 2-ом, а те старше представителей 3-го класса:", "Верно!" if first_class_older else "Неверно!")

In [ ]:
Pclass  Sex
1       female    34.611765
        male      41.281386
2       female    28.722973
        male      30.740707
3       female    21.750000
        male      26.507589
Name: Age, dtype: float64

Анализ утверждений:
1. В среднем мужчины 1-го класса старше 40 лет: Верно!
2. В среднем женщины 1-го класса старше 40 лет: Неверно!
3. Мужчины всех классов в среднем старше женщин того же класса: Верно!
4. В среднем люди в 1 классе старше, чем во 2-ом, а те старше представителей 3-го класса: Верно!

10. Сравните возраст у спасенных и у погибших пасажиров. Средний возраст погибших выше, верно?

In [ ]:
survived = titanic_df[titanic_df['Survived'] == 1]
dead = titanic_df[titanic_df['Survived'] == 0]
survived_age = round(survived['Age'].mean(), 2)
dead_age = round(dead['Age'].mean(), 2)
print("Возраст спасенных пасажиров:", survived_age)
print("Возраст погибших пасажиров:", dead_age)
print("Средний возраст погибших выше!") if dead_age > survived_age else print("Утверждение неверно")

In [ ]:
Возраст спасенных пасажиров: 28.34
Возраст погибших пасажиров: 30.63
Средний возраст погибших выше!